# Generated by Django 2.1.8 on 2019-05-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
